{% set name = "types-waitress" %}
{% set version = "2.1.4.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/types-waitress-{{ version }}.tar.gz
  sha256: 09ca667d0b07776a0e8c1e58161a55bdd6fc3d80ed880319aa40771c8d2435f0

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  commands:
    - test -f $SP_DIR/waitress-stubs/__init__.pyi


about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for waitress
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
