{% set name = "types-waitress" %}
{% set version = "3.0.0.20240423" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/types-waitress-{{ version }}.tar.gz
  sha256: ec3af592b5868ccf151645afc74d2e606cd5dec3ed326c9fd0259691b39430fe

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  commands:
    - test -f $SP_DIR/waitress-stubs/__init__.pyi


about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for waitress
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
